import { StyleSheet } from "react-native";

export const stylesLogin = StyleSheet.create({
  test: {
    marginTop: 5,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 30,
  },
  Box: {
    margin: '5%',
    borderRadius: 20,
    padding: 10,
    gap: 10,
    fontWeight: 'semibold',
    fontSize: 8,
    alignItems: 'flex-start',
    backgroundColor: '#D3D3D3',
  },
  inputBox: {
    width: '100%',
    height: 60,
    backgroundColor: '#C0C0C0',
    borderRadius: 20,
    padding: 20,
  },
  Text: {
    fontWeight: 'bold',
    fontSize: 20,
  },
  buttonTxt: {
    fontWeight: 'bold',
    fontSize: 15,
    marginTop: 20,
    marginEnd: 40,
    marginLeft: '10%',
    backgroundColor: '#00FF99',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '80%',
  },
  para: {
    fontWeight: '500',
    fontSize: 20,
    marginTop: 40,
    marginLeft: 20,
  },
  buttonSignUp: {
    fontWeight: 'bold',
    fontSize: 15,
    marginTop: 20,
    marginEnd: 40,
    marginLeft: '20%',
    backgroundColor: '#33CCFF',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '60%',
  },
});