import { StyleSheet } from 'react-native';
import { theme } from '../../globals/constants/constants';
import { brand, hp, wp } from '../../globals/globals';

export const stylesProfile = StyleSheet.create({
  container: {
    flex: 1,
    padding: wp(6),
  },
  heading: {
    fontSize: hp(3.8),
    fontWeight: 'bold',
    marginVertical: hp(2.4),
    alignSelf: 'center',
    color: theme.themePrimaryOrange,
  },
  imageWrapper: {
    alignSelf: 'center',
    marginVertical: hp(1),
    width: wp(30),
    height: wp(30),
    borderRadius: 18,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: brand.white,
    borderWidth: 1,
    borderColor: theme.themePrimaryOrange,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  cameraOutline: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: theme.themePrimaryOrange,
    borderRadius: 18,
    padding: 4,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  card: {
    backgroundColor: theme.boxColorOverPage,
    borderRadius: 18,
    padding: wp(5),
    elevation: 9,
    shadowColor: theme.shadowColor,
    shadowOpacity: 0.1,
    shadowRadius: 4,
    marginTop: hp(2.4),
  },
  logoutButton: {
    backgroundColor: theme.nonvegColor,
    paddingVertical: hp(1.8),
    marginTop: hp(3.5),
    marginBottom: hp(5.5),
    borderRadius: wp(2.5),
    alignItems: 'center',
  },
  logoutText: {
    color: theme.whiteText,
    fontSize: hp(2),
    fontWeight: '600',
  },
});
