import { StyleSheet } from 'react-native';
import { hp, lightTheme, wp } from '../../globals/globals';
import { theme } from '../../globals/constants/constants';

export const stylesSignUp = StyleSheet.create({
  heading: {
    marginTop: hp(0.5),
    marginBottom: hp(1),
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: hp(4),
  },
  Box: {
    margin: hp(4),
    marginTop: hp(2),
    marginBottom: hp(4),
    borderRadius: hp(6),
    gap: hp(2),
    padding: hp(5),
    backgroundColor: lightTheme.secondaryBackground,
    elevation: 4,
    shadowColor: theme.shadowColor,
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: hp(0.4) },
  },
  inputBox: {
    width: wp(70),
    height: hp(7),
    backgroundColor: theme.inputBoxColor,
    borderRadius: hp(3.5),
    paddingHorizontal: wp(6),
    alignSelf: 'center',
    fontSize: hp(2),
  },
  Text: {
    fontWeight: 'bold',
    fontSize: wp(5),
  },
  para: {
    fontWeight: '500',
    fontSize: wp(5),
    textAlign: 'center',
  },
  submitBtn: {
    marginTop: hp(1),
    alignSelf: 'center',
    paddingVertical: hp(1.5),
    borderRadius: hp(3),
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: wp(10),
  },
  BtnText: {
    fontWeight: 'bold',
    fontSize: wp(4),
    color: theme.cardColor,
  },
  textLogin: {
    fontWeight: 'bold',
    fontSize: wp(4),
    marginTop: hp(1),
    alignSelf: 'center',
    textAlign: 'center',
    width: wp(50),
    color: theme.themeSecondaryBlack,
  },
  link: {
    textAlign: 'center',
    fontSize: wp(4),
    color: theme.themePrimaryOrange,
    textDecorationLine: 'underline',
    marginBottom: hp(1),
  },
  radioGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: wp(5),
  },
  radioCircle: {
    height: hp(2.5),
    width: hp(2.5),
    borderRadius: hp(1.25),
    borderWidth: 2,
    borderColor: theme.themePrimaryOrange,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(2),
  },
  radioSelected: {
    height: hp(1.2),
    width: hp(1.2),
    borderRadius: hp(0.6),
    backgroundColor: theme.themePrimaryOrange,
  },
  radioLabel: {
    fontSize: hp(2.2),
    color: theme.color333,
  },
});
